Repository Super-Patos-Hackaton/frontend, pull requests merged in 2024-06, with the labels that each got.

#4 Merge config when everything is done.
  .eslintrc.json
  .gitignore
  .vscode/extensions.json
  README.md
  components.json
  next.config.mjs
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  public/img/logo.png
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/theme-provider.tsx
  src/components/theme-switcher.tsx
  src/components/ui/button.tsx
  src/components/ui/sample.test.tsx
  src/lib/utils.ts
  src/styles/fonts.ts
  tailwind.config.ts
  test/vitest-setup.ts
  tsconfig.json
  vitest.config.mts
Labels: enhancement

#9 update README
  README.md
Labels: documentation

#10 Update README summary
  README.md
Labels: documentation

#11 Update colors variables
  src/app/globals.css
  src/app/layout.tsx
  src/styles/globals.css
Labels: enhancement, Configuration

#13 Create typography components
  README.md
  pnpm-lock.yaml
  src/components/ui/typography.tsx
Labels: enhancement, New Feature

#16 Refactor typography component
  README.md
  src/components/ui/typography.tsx
Labels: documentation, enhancement

#14 Setup ESLint, Prettier with Husky and Commitlint
  .editorconfig
  .eslintignore
  .eslintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  README.md
  commitlint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/page.tsx
  src/components/theme-provider.tsx
  src/components/theme-switcher.tsx
  src/components/ui/button.tsx
  src/components/ui/sample.test.tsx
  src/components/ui/typography.tsx
  src/lib/utils.ts
  src/styles/fonts.ts
  src/styles/globals.css
Labels: documentation, enhancement, Configuration

#18 Add image selection prevention
  src/styles/globals.css
Labels: enhancement

#22 Sidebar Component
  package.json
  pnpm-lock.yaml
  public/img/white-logo.png
  src/app/layout.tsx
  src/components/nav-links-sidebar.tsx
  src/components/ui/sidebar/index.tsx
  src/components/ui/sidebar/sidebar.test.tsx
  src/config/nav-links.ts
  src/hooks/use-sidebar-toggle.ts
  src/hooks/use-store.ts
  src/styles/fonts.ts
  tailwind.config.ts
  test/vitest-setup.ts
Labels: enhancement, New Feature

#21 Create login & recovery screen
  .editorconfig
  .eslintignore
  .prettierignore
  .prettierrc.json
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  public/img/login-background-image-blur.webp
  public/img/login-background-image.webp
  src/app/(auth)/_components/loginAuthForm.test.tsx
  src/app/(auth)/_components/loginAuthForm.tsx
  src/app/(auth)/_components/phrase.tsx
  src/app/(auth)/_components/recoveryAuthForm.test.tsx
  src/app/(auth)/_components/recoveryAuthForm.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/recovery/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/typography.tsx
  tailwind.config.ts
Labels: New Feature

#31 Create challenge card component
  package.json
  pnpm-lock.yaml
  public/img/card-template.jpg
  src/components/ui/badge.tsx
  src/components/ui/challenge-card.tsx
Labels: enhancement, New Feature

#35 Create Challenges Completion Progress Widget
  package.json
  pnpm-lock.yaml
  src/components/challenges-completion.tsx
  src/components/ui/challenge-card.tsx
  src/components/ui/graphElements.tsx
  src/components/ui/widget.tsx
  src/components/user-level.tsx
  tailwind.config.ts
Labels: New Feature

#37 Create calendar component
  .eslintignore
  .prettierignore
  package.json
  pnpm-lock.yaml
  src/components/challenges-calendar.tsx
  src/components/ui/calendar-custom-day.tsx
  src/components/ui/calendar.tsx
  src/hooks/use-calendar.ts
  src/lib/utils.ts
  src/styles/globals.css
  src/types/challenges.ts
Labels: enhancement

#33 Profile Page
  package.json
  pnpm-lock.yaml
  src/app/dashboard/(dashboard)/layout.tsx
  src/app/dashboard/(dashboard)/profile/_components/most-used-techs-chart.tsx
  src/app/dashboard/(dashboard)/profile/_components/profile-card.tsx
  src/app/dashboard/(dashboard)/profile/_components/user-score-chart.tsx
  src/app/dashboard/(dashboard)/profile/page.tsx
  src/components/nav-links-sidebar.tsx
  src/components/ui/avatar.tsx
  src/components/ui/progress.tsx
  src/components/ui/sidebar/index.tsx
  src/components/ui/statistics/index.tsx
  src/config/icon-techs.tsx
  src/config/mocks/user-profile-page.ts
  src/config/nav-links.ts
  src/config/user-badges.tsx
Labels: enhancement, New Feature

#38 Fix/update color palette
  pnpm-lock.yaml
  src/app/(auth)/_components/loginAuthForm.tsx
  src/app/(auth)/_components/recoveryAuthForm.tsx
  src/components/ui/input.tsx
  src/components/ui/typography.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: bug, Configuration

#46 Create loading spinner component
  src/components/ui/loading-spinner.tsx
Labels: enhancement, New Feature

#45 Create Challenge Detail Page
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/app/(dashboard)/dashboard/challenges/[id]/_components/card-subtitle.tsx
  src/app/(dashboard)/dashboard/challenges/[id]/_components/submit-challenge-form.tsx
  src/app/(dashboard)/dashboard/challenges/[id]/page.tsx
  src/app/(dashboard)/dashboard/layout.tsx
  src/app/(dashboard)/dashboard/profile/_components/most-used-techs-chart.tsx
  src/app/(dashboard)/dashboard/profile/_components/profile-card.tsx
  src/app/(dashboard)/dashboard/profile/_components/user-score-chart.tsx
  src/app/(dashboard)/dashboard/profile/page.tsx
  src/app/layout.tsx
  src/components/ui/input.tsx
  src/components/ui/sidebar/index.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
  src/config/mocks/individual-challenges.ts
  tailwind.config.ts
Labels: enhancement, New Feature

#49 create home page
  src/app/(dashboard)/dashboard/page.tsx
  src/components/challenges-calendar.tsx
  src/components/challenges-completion.tsx
  src/components/ui/calendar.tsx
  src/components/ui/graphElements.tsx
  src/components/ui/widget.tsx
  src/components/user-level.tsx
  src/styles/globals.css
Labels: enhancement, New Feature

#47 Create Challenge Listing Filter Component
  package.json
  pnpm-lock.yaml
  src/components/filter-challenge.tsx
  src/components/ui/combobox.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/use-toast.ts
  src/config/mocks/filter-challenge.ts
Labels: New Feature

#50 Create Challenge Acceptance Page
  package.json
  pnpm-lock.yaml
  src/app/(dashboard)/dashboard/challenges/acceptance/[id]/_components/card-subtitle.tsx
  src/app/(dashboard)/dashboard/challenges/acceptance/[id]/_components/challenge-level-badge.tsx
  src/app/(dashboard)/dashboard/challenges/acceptance/[id]/page.tsx
  src/components/ui/challenge-card.tsx
  src/config/mocks/challenge-card.ts
  src/types/challenges.ts
Labels: enhancement, New Feature

#53 Refactor/update test ids
  pnpm-lock.yaml
  src/app/(dashboard)/dashboard/challenges/[id]/_components/submit-challenge-form.tsx
  src/app/(dashboard)/dashboard/challenges/acceptance/[id]/page.tsx
  src/app/(dashboard)/dashboard/profile/page.tsx
  src/components/challenges-calendar.tsx
  src/components/challenges-completion.tsx
  src/components/filter-challenge.tsx
  src/components/nav-links-sidebar.tsx
  src/components/theme-switcher.tsx
  src/components/ui/challenge-card.tsx
  src/components/ui/combobox.tsx
  src/components/ui/sidebar/index.tsx
Labels: bug, Configuration
